services:

  lint:
    build: .
    volumes:
      - ./android-project:/project
      - ./reports:/reports
      - gradle-cache:/root/.gradle

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./reports:/usr/share/nginx/html:ro

volumes:
  gradle-cache:
