plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.lintpratica'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.lintpratica"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {}
        release {
            minifyEnabled false
        }
    }

    lint {
        htmlReport = true
        xmlReport = true
        abortOnError = false
        checkAllWarnings = true
        warningsAsErrors = false
    }
}

dependencies {
    // Sem dependências externas — projeto mínimo para demonstração de Lint
}
